// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZrmZKLTFWWn_coh5cDqn6eS3qZH7nGDI',
    appId: '1:472798589356:web:20d0606d0dc6f302630a09',
    messagingSenderId: '472798589356',
    projectId: 'instagram-clone-beb9a',
    authDomain: 'instagram-clone-beb9a.firebaseapp.com',
    storageBucket: 'instagram-clone-beb9a.firebasestorage.app',
    measurementId: 'G-VE11WL5CP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzesr354DLNvMhL0dv0DG8-0Of00ASO9c',
    appId: '1:472798589356:android:4e29e9f3f8282f7e630a09',
    messagingSenderId: '472798589356',
    projectId: 'instagram-clone-beb9a',
    storageBucket: 'instagram-clone-beb9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdtsyxEWP49_Y8JcMXegC6yIWIL-VIViw',
    appId: '1:472798589356:ios:83bc84a4feaf62d9630a09',
    messagingSenderId: '472798589356',
    projectId: 'instagram-clone-beb9a',
    storageBucket: 'instagram-clone-beb9a.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdtsyxEWP49_Y8JcMXegC6yIWIL-VIViw',
    appId: '1:472798589356:ios:83bc84a4feaf62d9630a09',
    messagingSenderId: '472798589356',
    projectId: 'instagram-clone-beb9a',
    storageBucket: 'instagram-clone-beb9a.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZrmZKLTFWWn_coh5cDqn6eS3qZH7nGDI',
    appId: '1:472798589356:web:16f0c36c052508fb630a09',
    messagingSenderId: '472798589356',
    projectId: 'instagram-clone-beb9a',
    authDomain: 'instagram-clone-beb9a.firebaseapp.com',
    storageBucket: 'instagram-clone-beb9a.firebasestorage.app',
    measurementId: 'G-D61G05ZZL4',
  );
}
